apiVersion: v1
kind: Secret
metadata:
  name: egov-jwt-secret
  namespace: egov-app
type: Opaque
data:
  # echo -n '<JWT secret>' | base64
  TOKEN_ACCESS_SECRET: N0ZCODE0QjlEN0ZGQjNENjc1RUYxRjUyNUMxRDYxQjI1NDIyN0IzQjBBNzcxREREQkRGRTQxMTJBMUY0MkY2Ng==
  TOKEN_REFRESH_SECRET: N0ZCODE0QjlEN0ZGQjNENjc1RUYxRjUyNUMxRDYxQjI1NDIyN0IzQjBBNzcxREREQkRGRTQxMTJBMUY0MkY2Ng==
